# docker-compose.local.yml

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    container_name: kdkpbot
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
    command: poetry run python src/kdkpbot/main.py

  db:
    image: postgres:15
    container_name: kdkpbot-postgres
    environment:
      POSTGRES_DB: kdkp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d kdkp"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
