services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kdkpbot
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run pytest
